const Counter = require('../models/Counter');
const BarcodeGenerator = require('./barcodeGenerator');

/**
 * Atomically increments and returns the next number for a key.
 * When called with a transaction session, a rolled-back transaction also rolls
 * the counter back, so document numbers stay gap-free (important for GST invoices).
 */
async function nextSequence(key, session = null) {
  const doc = await Counter.findOneAndUpdate(
    { _id: key },
    { $inc: { seq: 1 } },
    { new: true, upsert: true, setDefaultsOnInsert: true, session }
  );
  return doc.seq;
}

/**
 * Generates a document number like  PREFIX/BRANCH/YEAR/00001
 *
 * @param {string} prefix       e.g. INV, KACHA, PUR, PAY
 * @param {string} branchCode   e.g. HO01
 * @param {object} session      mongoose session (optional)
 * @param {object} [unique]     { model, field } - when supplied, the number is checked against
 *                              existing documents (protects databases that already contain numbers
 *                              generated by older versions of this backend).
 */
async function nextDocNo(prefix, branchCode = 'HO', session = null, unique = null) {
  const year = new Date().getFullYear();
  const key = `${prefix}:${branchCode}:${year}`;

  for (let attempt = 0; attempt < 100; attempt++) {
    const seq = await nextSequence(key, session);
    const no = BarcodeGenerator.generateInvoiceNo(prefix, branchCode, seq);
    if (!unique) return no;
    const exists = await unique.model.exists({ [unique.field]: no }).session(session);
    if (!exists) return no;
  }
  throw new Error(`Unable to allocate a unique document number for ${key}`);
}

module.exports = { nextSequence, nextDocNo };
