/**
 * System-wide Constants for Jewellery ERP
 */
module.exports = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    BRANCH_MANAGER: 'BRANCH_MANAGER',
    SALES_MANAGER: 'SALES_MANAGER',
    SALES_EXECUTIVE: 'SALES_EXECUTIVE',
    PURCHASE_MANAGER: 'PURCHASE_MANAGER',
    INVENTORY_MANAGER: 'INVENTORY_MANAGER',
    ACCOUNTANT: 'ACCOUNTANT',
    CASHIER: 'CASHIER'
  },

  PERMISSIONS: {
    VIEW: 'VIEW',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    APPROVE: 'APPROVE',
    CANCEL: 'CANCEL',
    PRINT: 'PRINT',
    EXPORT: 'EXPORT'
  },

  METALS: {
    GOLD: 'GOLD',
    SILVER: 'SILVER',
    PLATINUM: 'PLATINUM',
    DIAMOND: 'DIAMOND',
    OTHER: 'OTHER'
  },

  PURITIES: {
    GOLD_24K: '24K',
    GOLD_22K: '22K',
    GOLD_20K: '20K',
    GOLD_18K: '18K',
    GOLD_14K: '14K',
    GOLD_9K: '9K',
    SILVER_999: '999',
    SILVER_925: '925',
    PLATINUM_950: '950'
  },

  BILL_TYPES: {
    KACHA: 'KACHA',
    PAKKA: 'PAKKA'
  },

  INVOICE_STATUSES: {
    DRAFT: 'DRAFT',
    CONFIRMED: 'CONFIRMED',
    PARTIAL: 'PARTIAL',
    PAID: 'PAID',
    DUE: 'DUE',
    CANCELLED: 'CANCELLED',
    CONVERTED: 'CONVERTED'
  },

  PAYMENT_MODES: {
    CASH: 'CASH',
    UPI: 'UPI',
    CARD: 'CARD',
    BANK_TRANSFER: 'BANK_TRANSFER',
    CHEQUE: 'CHEQUE',
    EXCHANGE: 'EXCHANGE',
    OTHER: 'OTHER'
  },

  PAYMENT_STATUSES: {
    SUCCESS: 'SUCCESS',
    REVERSED: 'REVERSED',
    PENDING: 'PENDING'
  },

  STOCK_MOVEMENT_TYPES: {
    PURCHASE: 'PURCHASE',
    SALE: 'SALE',
    SALE_RETURN: 'SALE_RETURN',
    PURCHASE_RETURN: 'PURCHASE_RETURN',
    EXCHANGE_IN: 'EXCHANGE_IN',
    EXCHANGE_OUT: 'EXCHANGE_OUT',
    TRANSFER_IN: 'TRANSFER_IN',
    TRANSFER_OUT: 'TRANSFER_OUT',
    ADJUSTMENT_IN: 'ADJUSTMENT_IN',
    ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
    OPENING: 'OPENING',
    DAMAGE: 'DAMAGE',
    LOSS: 'LOSS'
  },

  INVENTORY_STATUSES: {
    AVAILABLE: 'AVAILABLE',
    SOLD: 'SOLD',
    RESERVED: 'RESERVED',
    DAMAGED: 'DAMAGED',
    EXCHANGED: 'EXCHANGED'
  },

  ORDER_STATUSES: {
    NEW: 'NEW',
    CONFIRMED: 'CONFIRMED',
    MANUFACTURING: 'MANUFACTURING',
    QC: 'QC',
    READY: 'READY',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED'
  },

  MAKING_CHARGE_TYPES: {
    PER_GRAM: 'PER_GRAM',
    PERCENTAGE: 'PERCENTAGE',
    FIXED: 'FIXED'
  },

  GST_RATES: {
    JEWELLERY_TOTAL: 3.0,
    CGST: 1.5,
    SGST: 1.5,
    IGST: 3.0
  },

  AUDIT_ACTIONS: {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    APPROVE: 'APPROVE',
    CANCEL: 'CANCEL',
    CONVERT: 'CONVERT',
    PAYMENT: 'PAYMENT',
    STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
    RETURN: 'RETURN'
  }
};
